# The location of the service's public webserver.'
domain = "http://localhost:8000"

# How many days sites are retained.
default_retention = 7

# The maximum size for the unpacked site in bytes.
max_site_size = 52428800  # 50 MiB

# The root where files are served from.
web_root = "/srv/tmpweb/www/"

# The location of the service's database.
database_location = "/srv/tmpweb/tmpweb.db"
