# The location of the service's public webserver.'
domain = "https://tmpweb.net"

# How many days sites are retained.
default_retention = 7

# The maximum size for the unpacked site in bytes.
max_site_size = 52428800  # 50 MiB

# The root where files are served from.
web_root = "/var/www/tmpweb/html"

# The location of the service's database.
database_location = "/var/www/tmpweb/tmpweb.db"
